CUDA_VISIBLE_DEVICES=1 nohup bash /223040263/wanlong/LLM_Retreival/RAG4RE/src/run_rams_baseline_llama3_no_diversity_rag.sh > run_rams_baseline_llama3_no_diversity_rag_new.log
CUDA_VISIBLE_DEVICES=1 nohup bash /223040263/wanlong/LLM_Retreival/RAG4RE/src/run_rams_baseline_llama3_random_rag.sh > run_rams_baseline_llama3_random_rag_new.log
CUDA_VISIBLE_DEVICES=1 nohup bash /223040263/wanlong/LLM_Retreival/RAG4RE/src/run_rams_baseline_qwen2_random_rag.sh > run_rams_baseline_qwen2_random_rag_new.log
CUDA_VISIBLE_DEVICES=1 nohup bash  /223040263/wanlong/LLM_Retreival/RAG4RE/src/run_wiki_ace_baseline_llama3_random_rag.sh > run_wiki_ace_baseline_llama3_random_rag_new.log
CUDA_VISIBLE_DEVICES=1 nohup bash /223040263/wanlong/LLM_Retreival/RAG4RE/src/run_wiki_ace_baseline_llama3_no_diversity_rag.sh > run_wiki_ace_baseline_llama3_no_diversity_rag_new.log
CUDA_VISIBLE_DEVICES=1 nohup bash /223040263/wanlong/LLM_Retreival/RAG4RE/src/run_wiki_ace_baseline_qwen2_random_rag.sh > run_wiki_ace_baseline_qwen2_random_rag_new.log 

